# Generated by Django 6.0.3 on 2026-03-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='public_showcase',
        ),
    ]
