# Generated by Django 6.0.3 on 2026-03-29 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='studysession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
