# Generated by Django 6.0.3 on 2026-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tracker', '0002_alter_subject_unique_together_remove_subject_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.CharField(choices=[('quantitative_aptitude', 'Quantitative Aptitude'), ('general_reasoning', 'General Reasoning'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('polity', 'Polity'), ('economy', 'Economy'), ('general_science', 'General Science')], max_length=50),
        ),
    ]
