# Generated by Django 6.0.3 on 2026-03-29 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_circles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='study_circles.studycircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_circle_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('circle', 'user')},
            },
        ),
    ]
