# Generated by Django 6.0.3 on 2026-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_circles', '0002_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycircle',
            name='allow_join_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studycircle',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
