# Generated by Django 6.0.3 on 2026-03-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_circles', '0003_studycircle_allow_join_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycircle',
            name='allow_join_requests',
        ),
        migrations.RemoveField(
            model_name='studycircle',
            name='is_private',
        ),
    ]
