# Generated by Django 6.0.3 on 2026-04-16 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_circles', '0005_studycircle_allow_join_requests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studycircle',
            name='discussion_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studycircle',
            name='discussion_restricted_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studycircle',
            name='resource_permissions',
            field=models.CharField(choices=[('admin_only', 'Admin Only'), ('all_members', 'All Members')], default='all_members', max_length=20),
        ),
        migrations.CreateModel(
            name='UserCircleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_resources', models.BooleanField(default=True)),
                ('notify_join_requests', models.BooleanField(default=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='study_circles.studycircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'circle')},
            },
        ),
    ]
