# Generated by Django 6.0.3 on 2026-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_circles', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycircle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
