# Generated by Django 6.0.3 on 2026-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='exam_type',
            field=models.CharField(choices=[('UPSC', 'UPSC'), ('SSC', 'SSC'), ('Banking', 'Banking'), ('Railways', 'Railways'), ('State PSC', 'State PSC'), ('NEET', 'NEET'), ('JEE', 'JEE')], default='SSC', max_length=100),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Reasoning', 'Reasoning'), ('General Knowledge', 'General Knowledge'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English')], default='General Knowledge', max_length=100),
        ),
    ]
