# Generated by Django 6.0.3 on 2026-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_mocktest_difficulty_mocktest_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
