# Generated by Django 6.0.3 on 2026-03-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_alter_question_difficulty_alter_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='subject',
            field=models.CharField(choices=[('quantitative_aptitude', 'Quantitative Aptitude'), ('general_reasoning', 'General Reasoning'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('polity', 'Polity'), ('general_science', 'General Science'), ('economy', 'Economy'), ('current_affairs', 'Current Affairs')], default='general_science', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('quantitative_aptitude', 'Quantitative Aptitude'), ('general_reasoning', 'General Reasoning'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('polity', 'Polity'), ('general_science', 'General Science'), ('economy', 'Economy'), ('current_affairs', 'Current Affairs')], db_index=True, max_length=50),
        ),
    ]
