# Generated by Django 6.0.3 on 2026-04-22 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_alter_mocktest_subject_alter_question_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(choices=[('quantitative_aptitude', 'Quantitative Aptitude'), ('general_reasoning', 'General Reasoning'), ('english', 'English'), ('history', 'History'), ('geography', 'Geography'), ('polity', 'Polity'), ('economy', 'Economy'), ('general_science', 'General Science'), ('current_affairs', 'Current Affairs')], max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='study_materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
