# Generated by Django 6.0.3 on 2026-04-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0006_favoritematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main API Key', max_length=100)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_circles', models.BooleanField(default=False)),
                ('can_manage_materials', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_language', models.CharField(default='en', max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_signup', models.BooleanField(default=True)),
                ('require_strong_password', models.BooleanField(default=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('api_access_enabled', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(default='daily', max_length=20)),
                ('storage_limit_mb', models.IntegerField(default=5000)),
                ('auto_cleanup', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
