# Generated by Django 6.0.3 on 2026-03-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
        ('mock_tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptanswer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_option_str',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='admin_module.question'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='mock_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='admin_module.mocktest'),
        ),
    ]
